// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MealMemos.iOS
{
	public partial class CustomTopBar : UIViewController
	{
		public CustomTopBar (IntPtr handle) : base (handle)
		{
		}
	}
}
