// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MealMemos.iOS
{
	public partial class CustomPageViewController : UIPageViewController
	{
        public Team team;
        public CustomPageViewController (IntPtr handle) : base (handle)
		{
            
		}
	}
}