// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using UIKit;
using Xamarin.Essentials;
using Masonry;
using System.Diagnostics;
using MealMemos.Models;
using System.Linq;

namespace MealMemos.iOS
{
    public partial class HomepageViewController : UIViewController, IUIPageViewControllerDataSource
    {
        private Team team;
        private int currentMemberIndex = 0;
        private List<string> bgcolors;
        private UIPageViewController pageViewController;
        private UIPageControl pageControl;

        public HomepageViewController(IntPtr handle) : base(handle)
        {
            this.team = new Team();
            this.bgcolors = SetColors();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            configurePageViewController();
        }

        private void configurePageViewController()
        {
            this.pageViewController = (CustomPageViewController)Storyboard?.InstantiateViewController(identifier: "CustomPageViewController");
            this.pageViewController.DataSource = this;
            this.AddChildViewController(this.pageViewController);
            this.pageViewController.View.TranslatesAutoresizingMaskIntoConstraints = false;
            this.pageViewController.DidMoveToParentViewController(this);
            this.contentView.AddSubview(this.pageViewController.View);

            this.pageViewController.DidFinishAnimating += this.PageViewControllerDidFinishAnimating;

            this.pageViewController.View.MakeConstraints(make =>
            {
                make.Width.EqualTo(this.contentView);
                make.Height.EqualTo(this.contentView);
                make.Center.EqualTo(this.contentView);
            });

            this.pageControl = new UIPageControl
            {
                CurrentPageIndicatorTintColor = UIColor.White,
                PageIndicatorTintColor = UIColor.Black,
                TranslatesAutoresizingMaskIntoConstraints = false,
                Pages = team.MemberCount,
                CurrentPage = 0
            };
            this.contentView.Add(pageControl);

            this.pageControl.MakeConstraints(make =>
            {
                make.Bottom.EqualTo(this.contentView.Bottom()).Offset(-100);
                make.CenterX.EqualTo(this.contentView);
            });

            var startingViewController = MemberViewControllerAtIndex(currentMemberIndex);
            List<MemberViewController> allMembers = new List<MemberViewController>
            {
                startingViewController
            };
            this.pageViewController.SetViewControllers(allMembers.ToArray(), UIPageViewControllerNavigationDirection.Forward, false, null);
        }

        private void PageViewControllerDidFinishAnimating(object sender, UIPageViewFinishedAnimationEventArgs e)
        {
            if (e.Finished && e.Completed)
            {
                // Get children of pageViewController
                // Get the current displayed
                // Cast as MemberViewController
                // Get index
                this.pageControl.CurrentPage = (this.pageViewController.ViewControllers?.FirstOrDefault() as MemberViewController).index;
            }
        }

        private MemberViewController MemberViewControllerAtIndex(int index)
        {
            if (index >= team.MemberCount || team.MemberCount == 0)
            {
                return null;
            }
            var memberViewController = (MemberViewController)Storyboard.InstantiateViewController("MemberViewController");
            memberViewController.firstnameText = this.team[index].Firstname;
            memberViewController.index = index;
            if (index >= this.bgcolors.Count)
                memberViewController.View.BackgroundColor = UIColor.Orange;
            else
                memberViewController.View.BackgroundColor = ColorConverters.FromHex(this.bgcolors[index]).ToPlatformColor();
            return memberViewController;
        }

        public UIViewController GetPreviousViewController(UIPageViewController pageViewController, UIViewController referenceViewController)
        {
            var current = (MemberViewController)referenceViewController;
            var index = current.index;
            if (index == 0)
            {
                return null;
            }
            index--;
            return this.MemberViewControllerAtIndex(index);
        }

        public UIViewController GetNextViewController(UIPageViewController pageViewController, UIViewController referenceViewController)
        {
            var current = (MemberViewController)referenceViewController;
            var index = current.index;
            if (index == team.MemberCount)
            {
                return null;
            }
            index++;
            return this.MemberViewControllerAtIndex(index);
        }

        private List<string> SetColors()
        {
            List<string> colors = new List<string>
            {
                Color.Blue,
                Color.Gray,
                Color.Green,
                Color.Yellow,
                Color.Magenta
            };
            return colors;
        }
    }
}
