// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Xamarin.Essentials;
using Plugin.FirebaseAuth;
using UIKit;
using Newtonsoft.Json;
using Firebase.Auth;
using System.Collections.Generic;

namespace MealMemos.iOS
{

    public partial class LoginViewController : UIViewController
    {
        private const string userKey = "user";
        public LoginViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            if (this.hasAlreadyCreateAccount())
            {
                var controller = this.Storyboard.InstantiateViewController("MainViewController") as MainViewController;
                this.NavigationController.PushViewController(controller, true);
            }
            this.loginBtn.TouchUpInside += LoginAsync;
            this.resetBtn.TouchUpInside += Reset;
        }

        private async void LoginAsync(object sender, EventArgs e)
        {
            
            if (this.IsValidLogin())
            {
                var success = await this.SignInFirebaseAsync(this.emailTextView.Text, this.passTextView.Text);

                if (success != null)
                {
                    this.StoreUserInfo(success);
                    var controller = this.Storyboard.InstantiateViewController("MainViewController") as MainViewController;
                    this.NavigationController.PushViewController(controller, true);
                }
                else
                {
                    Console.WriteLine("Mealmemos : LoginViewController : Erreur creation compte");
                }
            }
            
        }

        private void StoreUserInfo(IUser user)
        {
            Preferences.Set(userKey, JsonConvert.SerializeObject(user));
        }

        private async Task<IUser> SignInFirebaseAsync(string email, string password)
        {
            try
            {
                var result = await CrossFirebaseAuth.Current.Instance.CreateUserWithEmailAndPasswordAsync(email, password);
                if (result.User != null)
                {
                    return result.User;
                }
            }catch (Exception e)
            {
                Console.WriteLine(e);
                return null;
            }
           
            return null;
        }

        private bool IsValidLogin()
        {
            if (this.IsValidEmail() &&
                this.passTextView.Text != String.Empty &&
                this.confirmTextView.Text != String.Empty &&
                this.confirmTextView.Text.Equals(this.passTextView.Text))
            {
                return true;
            }

            return false;
        }

        private void Reset(object sender, EventArgs e)
        {
            this.emailTextView.Text = String.Empty;
            this.passTextView.Text = String.Empty;
            this.confirmTextView.Text = String.Empty;
        }

        private bool IsValidEmail()
        {
            try
            {
                return Regex.IsMatch(this.emailTextView.Text,
                    @"^(?("")("".+?(?<!\\)""@)|(([0-9a-z]((\.(?!\.))|[-!#\$%&'\*\+/=\?\^`\{\}\|~\w])*)(?<=[0-9a-z])@))" +
                    @"(?(\[)(\[(\d{1,3}\.){3}\d{1,3}\])|(([0-9a-z][-0-9a-z]*[0-9a-z]*\.)+[a-z0-9][\-a-z0-9]{0,22}[a-z0-9]))$",
                    RegexOptions.IgnoreCase, TimeSpan.FromMilliseconds(250));
            }
            catch (RegexMatchTimeoutException)
            {
                return false;
            }
        }

        private bool hasAlreadyCreateAccount()
        {
            var user = Preferences.Get(userKey, null);
            return user == null ? false : true;
        }
    }
}
