// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MealMemos.iOS
{
	public partial class MemberViewController : UIViewController
	{
        public string firstnameText;
        public int index;
        public MemberViewController (IntPtr handle) : base (handle)
		{
		}

        public MemberViewController()
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            firstnameLabel.Text = firstnameText;
        }
	}
}
